default_platform(:android)

platform :android do
  lane :internal do
    ensure_git_branch(
      branch: 'internal'
      )

    android_set_version_code
    version_code = android_get_version_code
    version_name = android_get_version_name  

    gradle(
      task: "clean bundle",
      flavor: "store",
      build_type: "Release",
      )

    git_commit(
      path: ["./*.gradle"], 
      message: "Bump version to #{version_name} - build #{version_code}",
      allow_nothing_to_commit: false
      )

    add_git_tag(
      grouping: "fastlane-builds",
      prefix: "v",
      postfix: "-#{version_name}",
      build_number: "#{version_code}"
      )    
    supply(
      track: "internal",
      skip_upload_metadata: true
      )
  end
end
