# update_fastlane

default_platform(:android)

platform :android do
  lane :internal do
 	sh("git", "checkout", "internal")
  	sh("git", "merge", "--squash", "bugfix")
  	sh("git", "commit")

  	git_switch_branch(branch: "internal")
  	android_set_version_code(
    	gradle_file: "demo/build.gradle" # optional
  	)
 
  	version_code = android_get_version_code(
    	gradle_file: "demo/build.gradle" # optional
  	)

  	version_name = android_get_version_name(
    	gradle_file: "demo/build.gradle" # optional
  	)		

  	gradle(task: "clean assembleRelease")


  	commit_android_version_bump(
    	gradle_file_folder:"demo"
  	)

	add_git_tag(
 	 	grouping: "fastlane-builds",
 	 	prefix: "v",
  		postfix: "-#{version_name}",
  		build_number: "#{version_code}"
	)
    # supply(
    #   track: "internal",
    #   skip_upload_metadata: true
    #   )

  end
end